#/home/wenyongyan/文档/acrl/venv/bin/python run.py --type goal_gan --learner ppo --env minigrid-b --seed 1
#/home/wenyongyan/文档/acrl/venv/bin/python run.py --type goal_gan --learner ppo --env minigrid-b --seed 2
#/home/wenyongyan/文档/acrl/venv/bin/python run.py --type goal_gan --learner ppo --env minigrid-b --seed 3
#/home/wenyongyan/文档/acrl/venv/bin/python run.py --type goal_gan --learner ppo --env minigrid-b --seed 4
#/home/wenyongyan/文档/acrl/venv/bin/python run.py --type goal_gan --learner ppo --env minigrid-b --seed 5
#/home/wenyongyan/文档/acrl/venv/bin/python run.py --type goal_gan --learner ppo --env minigrid-b --seed 6
#/home/wenyongyan/文档/acrl/venv/bin/python run.py --type goal_gan --learner ppo --env minigrid-b --seed 7
#/home/wenyongyan/文档/acrl/venv/bin/python run.py --type goal_gan --learner ppo --env minigrid-b --seed 8
#/home/wenyongyan/文档/acrl/venv/bin/python run.py --type goal_gan --learner ppo --env minigrid-b --seed 9
#/home/wenyongyan/文档/acrl/venv/bin/python run.py --type goal_gan --learner ppo --env minigrid-b --seed 10
#/home/wenyongyan/文档/acrl/venv/bin/python run.py --type goal_gan --learner ppo --env minigrid-c --seed 1
#/home/wenyongyan/文档/acrl/venv/bin/python run.py --type goal_gan --learner ppo --env minigrid-c --seed 2
#/home/wenyongyan/文档/acrl/venv/bin/python run.py --type goal_gan --learner ppo --env minigrid-c --seed 3
#/home/wenyongyan/文档/acrl/venv/bin/python run.py --type goal_gan --learner ppo --env minigrid-c --seed 4
#/home/wenyongyan/文档/acrl/venv/bin/python run.py --type goal_gan --learner ppo --env minigrid-c --seed 5
#/home/wenyongyan/文档/acrl/venv/bin/python run.py --type goal_gan --learner ppo --env minigrid-c --seed 6
#/home/wenyongyan/文档/acrl/venv/bin/python run.py --type goal_gan --learner ppo --env minigrid-c --seed 7
#/home/wenyongyan/文档/acrl/venv/bin/python run.py --type goal_gan --learner ppo --env minigrid-c --seed 8
#/home/wenyongyan/文档/acrl/venv/bin/python run.py --type goal_gan --learner ppo --env minigrid-c --seed 9
#/home/wenyongyan/文档/acrl/venv/bin/python run.py --type goal_gan --learner ppo --env minigrid-c --seed 10

/home/wenyongyan/文档/acrl/venv/bin/python run.py --type goal_gan --learner ppo --env minigrid-a --seed 6
/home/wenyongyan/文档/acrl/venv/bin/python run.py --type goal_gan --learner ppo --env minigrid-a --seed 7
/home/wenyongyan/文档/acrl/venv/bin/python run.py --type goal_gan --learner ppo --env minigrid-a --seed 8
/home/wenyongyan/文档/acrl/venv/bin/python run.py --type goal_gan --learner ppo --env minigrid-a --seed 9
/home/wenyongyan/文档/acrl/venv/bin/python run.py --type goal_gan --learner ppo --env minigrid-a --seed 10